on:
  push:
    branches: [master]
name: docs
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "Neovim >= 0.11.0"
          demojify: true
          treesitter: true
          # exclude the toplevel `# codesettings.nvim` heading
          # because it makes the section tags have duped project name
          shiftheadinglevelby: -1
      - name: Generate helptags
        run: nix develop .#ci --command nvim --headless -c 'helptags doc' -c 'qa'
      - name: Run benchmarks
        run: nix develop .#ci --command just bench
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(ci): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
