name: Update Schemas
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # every day at 1AM
jobs:
  schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: folke/github/neovim@main
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix develop .#ci --command just build
      - name: Submit PR with changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): auto-generate schemas"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
